apiVersion: v1
kind: Pod
metadata:
  name: test-file
spec:
  containers:
    - name: env-test
      image: alpine
      command: ["/bin/sh", "-c", "env; sleep 3600"]
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          cpu: "100m"
          memory: "64Mi"
        limits:
          cpu: "200m"
          memory: "128Mi"
      env:
        - name: java
          valueFrom:
            configMapKeyRef: # 从cm文件映射进入容器
              name: test-env-map
              key: java
        - name: k2
          valueFrom:
            configMapKeyRef:
              name: test-env-map
              key: k2
      volumeMounts: # 与 volumes 中的 name 一致
        - mountPath: /etc/config # 将volumes加载到哪个路径下
          name: db-config # 与volumes name一致
          readOnly: true
  volumes:
    - name: db-config
      configMap:
        name: test-config # 这里写cm名字
        items: #不指定, 则所有映射为文件
          - key: db.properties # 将key对应的value提取出来
            path: db.p # 转为文件, 自己命名
  restartPolicy: Never
