apiVersion: v1
kind: Pod
metadata:
  name: empty-pod
  labels:
    name: empty-pod
spec:
  containers:
    - name: empty-pod1
      image: alpine
      command: ["bin/sh", "-c", "sleep 3600;"]
      volumeMounts:
        - mountPath: /cache
          name: cache-volume
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          cpu: "100m"
          memory: "100Mi"
    - name: empty-pod2
      image: alpine
      command: ["bin/sh", "-c", "sleep 3600;"]
      volumeMounts:
        - mountPath: /opt
          name: cache-volume
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          cpu: "100m"
          memory: "100Mi"
  volumes:
    - name: cache-volume
      emptyDir: {}
