apiVersion: v1 # API 版本，指定所使用的 Kubernetes API 版本
kind: Service # 资源类型，这里定义一个 Service（服务）
metadata:
  name: nginx # Service 的名称
  labels:
    app: nginx # Service 的标签，用于标识和选择相关的 Pod
spec:
  ports:
    - port: 80 # Service 暴露的端口号，外部通过此端口访问服务
      name: web # 端口名称，可用于服务发现
  clusterIP: None # 指定为无头服务（Headless Service），适用于 StatefulSet
  selector:
    app: nginx # Service 的选择器，匹配具有该标签的 Pod

---
apiVersion: apps/v1 # API 版本，指定所使用的 Kubernetes API 版本
kind: StatefulSet # 资源类型，这里定义一个 StatefulSet（有状态副本集）
metadata:
  name: web # StatefulSet 的名称
spec:
  serviceName: "nginx" # 与 StatefulSet 关联的 Service 名称，需与上面定义的 Service 名称一致
  replicas: 2 # Pod 副本数量，指定运行的 Pod 数量
  selector:
    matchLabels:
      app: nginx # 选择器，匹配具有该标签的 Pod，需与模板中的标签一致
  template: # Pod 模板，定义了创建的 Pod 的配置
    metadata:
      labels:
        app: nginx # Pod 的标签，需与上面的选择器匹配
    spec:
      terminationGracePeriodSeconds: 10 # 优雅终止的等待时间，单位为秒
      containers:
        - name: nginx # 容器名称
          image: nginx:latest # 使用的容器镜像及版本
          ports:
            - containerPort: 80 # 容器内部监听的端口号
              name: web # 端口名称
